language: cpp
compiler: clang

install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get -y install libeigen3-dev
  - sudo apt-get -y upgrade cmake
  - sudo apt-get -y install qt5-default

script:
  - ./build.sh
  - build/test-runner

notifications:
  email: justbuchanan@gmail.com
